from typing import overload, override


class ANSICode:
    def __init__(self, value: str) -> None: ...
    def __repr__(self) -> str: ...
    def __call__(self) -> None: ...
    @property
    def value(self) -> str: ...


class ANSIColorCode(ANSICode):
    def __init__(self, *codes: int) -> None: ...
    @overload
    def __add__(self, other: str) -> str: ...
    @overload
    def __add__(self, other: "ANSIColorCode") -> "ANSIColorCode": ...
    @overload
    def __radd__(self, other: str) -> str: ...
    @overload
    def __radd__(self, other: "ANSIColorCode") -> "ANSIColorCode": ...
    @property
    @override
    def value(self) -> str: ...
    @property
    def codes(self) -> list[int]: ...
    @property
    def is_RGB(self) -> bool: ...
